<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="csulpizi.CustomAccessibility" Version="1.0.3" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.17.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.12" />
    <PackageReference Include="Riok.Mapperly" Version="4.3.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.23.0" />
    <PackageReference Include="System.Security.Cryptography.Pkcs" Version="10.0.12" />
    <PackageReference Include="WebPush" Version="1.0.13" />
  </ItemGroup>

</Project>
