import { StyleSheet } from "react-native";
import { theme } from "@/theme/theme";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  scrollContent: { flexGrow: 1 },
  header: { alignItems: "center", gap: 8, marginTop: 8, marginBottom: 20 },
  title: { fontSize: 28, fontWeight: "800", letterSpacing: -0.6, marginTop: 8 },
  subtitle: { fontSize: 15, textAlign: "center", lineHeight: 22 },
  wideRow: { flexDirection: "row", gap: 24, alignItems: "flex-start" },
  wideCol: { flex: 1 },
  searchCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    padding: theme.spacing.xl,
    gap: theme.spacing.md,
    width: "100%",
    ...theme.shadows.md,
  },
  label: { ...theme.typography.label, letterSpacing: 0.2 },
  searchBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
    ...theme.buttonSizes.lg,
    borderRadius: theme.borderRadius.lg,
    marginTop: 4,
  },
  searchBtnText: { color: theme.colors.white, ...theme.typography.bodyBold, fontWeight: "700" },
  helpText: { ...theme.typography.caption, textAlign: "center", lineHeight: 18, marginTop: 4 },
  resultCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    padding: theme.spacing.xxl,
    marginTop: theme.spacing.xl,
    width: "100%",
    alignItems: "center",
    gap: theme.spacing.lg,
    ...theme.shadows.md,
  },
  notFound: { ...theme.typography.body, textAlign: "center" },
  detailCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    overflow: "hidden",
    ...theme.shadows.md,
  },
  cardHeader: {
    alignItems: "center",
    gap: theme.spacing.xsm,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.xl,
    paddingBottom: theme.spacing.lg,
  },
  resultHeader: { flexDirection: "row", alignItems: "center", gap: theme.spacing.sm },
  resultTitle: { ...theme.typography.h3 },
  refBadge: {
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
  },
  refText: { ...theme.typography.bodyBold, fontWeight: "700", letterSpacing: 0.3 },
  divider: { height: 1 },
  refBadgeRow: { flexDirection: "row", alignItems: "center", gap: theme.spacing.sm },
  copyBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: theme.spacing.xsm,
    paddingVertical: theme.spacing.xxs,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
  },
  copyBtnText: { ...theme.typography.caption, fontWeight: "600" },
  iconStrip: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    marginTop: 10,
    paddingVertical: theme.spacing.xsm,
    ...theme.shadows.md,
  },
  iconGroup: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacing.md,
  },
  iconGroupLabel: { fontSize: 11, fontWeight: "800", letterSpacing: 0.6, marginRight: 2 },
  iconGroupRow: { flexDirection: "row" },
  iconBtn: { padding: theme.spacing.xsm, borderRadius: theme.borderRadius.md },
  iconSep: { width: 1, alignSelf: "stretch" },
  actionsRow: { flexDirection: "row", gap: 10, marginTop: 10 },
  actionCard: {
    flex: 1,
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    overflow: "hidden",
    ...theme.shadows.md,
  },
  mapsWrap: { padding: 16, gap: 10, flex: 1 },
  mapsTitle: { fontSize: 11, fontWeight: "700", letterSpacing: 0.8, textTransform: "uppercase" },
  mapBtnsRow: { flexDirection: "row", gap: 8 },
  mapBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 8,
    flex: 1,
    justifyContent: "center",
  },
  mapBtnText: { fontSize: 12, fontWeight: "600" },
  cancelSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginTop: 10,
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: 14,
    ...theme.shadows.md,
  },
  cancelBtnText: { color: theme.colors.error, ...theme.typography.bodyBold },
  recentSection: { marginTop: theme.spacing.xl, gap: theme.spacing.xsm, width: "100%" },
  recentTitle: {
    ...theme.typography.labelSmall,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  recentCard: {
    borderRadius: theme.borderRadius.card,
    borderWidth: 1,
    padding: 14,
    ...theme.shadows.md,
  },
  recentCardRow: { flexDirection: "row", alignItems: "center", gap: theme.spacing.md },
  recentRef: { fontSize: 14, fontWeight: "700", letterSpacing: -0.2, flex: 1 },
  recentMeta: { ...theme.typography.caption },
});
