import { StyleSheet } from "react-native";
import { theme } from "@/theme/theme";

export const styles = StyleSheet.create({
  providerBlock: { gap: theme.spacing.sm },
  providerGrid: { flexDirection: "row", flexWrap: "wrap", gap: theme.spacing.sm },
  providerCard: {
    flex: 1,
    minWidth: 130,
    borderWidth: 1,
    borderRadius: theme.borderRadius.xl,
    padding: theme.spacing.md,
    paddingHorizontal: 14,
    gap: theme.spacing.xs,
    position: "relative",
  },
  providerCardSelected: {
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  providerIcon: {
    width: 32,
    height: 32,
    borderRadius: theme.borderRadius.md,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: theme.spacing.xs,
  },
  providerName: { fontSize: 13.5, fontWeight: "600" },
  providerHint: { fontSize: 11.5 },
  providerCheck: {
    position: "absolute",
    top: theme.spacing.xsm,
    right: theme.spacing.xsm,
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
  },

  connectionBlock: { gap: theme.spacing.xxs },
  fieldRow: { flexDirection: "row", gap: theme.spacing.xsm },
  fieldRowSpaced: { marginTop: theme.spacing.xs },
  fieldFlex: { flex: 1 },
  fieldSpaced: { marginTop: theme.spacing.xs },
  portRow: { flexDirection: "row", gap: theme.spacing.xxs, alignItems: "center" },
  portInput: { width: 80 },
  portPresets: { flexDirection: "row", gap: theme.spacing.xs, flex: 1 },
  portPreset: {
    paddingHorizontal: theme.spacing.xsm,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
  },
  portPresetText: { fontSize: 12 },

  encryptionRow: { flexDirection: "row", gap: theme.spacing.xxs },
  encryptionOption: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 9,
    paddingHorizontal: theme.spacing.xsm,
    borderRadius: theme.borderRadius.lg,
    borderWidth: 1,
  },
  encryptionOptionWithIcon: { flexDirection: "row", gap: theme.spacing.xxs },
  encryptionLabel: { fontSize: 13, fontWeight: "400" },
  encryptionLabelOn: { fontWeight: "500" },

  passwordRow: { flexDirection: "row", gap: theme.spacing.sm, alignItems: "center" },
  passwordInput: { flex: 1 },
  passwordToggle: { padding: theme.spacing.sm },
  blockGap: { height: theme.spacing.sm },

  rightColumn: { gap: 14 },
  form: { gap: theme.spacing.xl },
  columnsWide: { flexDirection: "row", gap: 22, alignItems: "flex-start" },
  columnsNarrow: { gap: theme.spacing.xl },
  rightColumnWide: { width: 340 },

  saveBanner: {
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    padding: theme.spacing.xsm,
  },
  saveBannerText: { flex: 1 },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    paddingTop: 14,
    borderTopWidth: 1,
    borderStyle: "dashed",
  },
  footerHint: { fontSize: 12, flex: 1 },
});
